//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF2022User311_1_NN_LibWPF.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public DoctorSchedule()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTimeSchedule { get; set; }
        public System.TimeSpan EndTimeSchedule { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Doctors Doctors { get; set; }
    }
}
