//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF2022User311_1_NN_LibWPF.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public Doctors()
        {
            this.DoctorSchedule = new HashSet<DoctorSchedule>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string LastName { get; set; }
        public int CabinetNumber { get; set; }
        public int SpecializationId { get; set; }
    
        public virtual Specializations Specializations { get; set; }
        public virtual ICollection<DoctorSchedule> DoctorSchedule { get; set; }
    }
}
