//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF2022User311_1_NN_LibWPF.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genders
    {
        public Genders()
        {
            this.Patients = new HashSet<Patients>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Patients> Patients { get; set; }
    }
}
