//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF2022User311_1_NN_LibWPF.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public Patients()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public string IdPatient { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string GenderCode { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
